// JsFromRoutes CacheKey 81657c25dae79b6c6f473149ef21023e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  whoami: /* #__PURE__ */ definePathHelper('get', '/current_user/whoami'),
}
