// JsFromRoutes CacheKey 03eca92764ba2879ecd2bf6a913e76a0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/forward_auth'),
  login: /* #__PURE__ */ definePathHelper('get', '/forward_auth/login'),
}
