// JsFromRoutes CacheKey 788baf44f83c0cbff91e45f9365c1f91
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: /* #__PURE__ */ definePathHelper('get', '/session/logout'),
  session: /* #__PURE__ */ definePathHelper('delete', '/session'),
  new: /* #__PURE__ */ definePathHelper('get', '/session/new'),
  create: /* #__PURE__ */ definePathHelper('post', '/session'),
}
