---
openapi: 3.0.1
info:
  title: API V1
  version: v1
consumes:
- application/json
produces:
- application/json
paths:
  "/current_user":
    get:
      summary: whoami
      operationId: Whoami
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                name: CurrentUserWhoamiResponse
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  username:
                    type: string
                required:
                - id
                - name
                - username
        '401':
          description: unauthorized
  "/admin/groups":
    get:
      summary: list
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                name: GroupsListResponse
                type: array
                items:
                  "$ref": "#/components/schemas/group_response"
        '401':
          description: unauthorized
    post:
      summary: create
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/group_response"
        '422':
          description: unprocessible entitiy
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/group_errors"
                name: GroupCreateErrorResponse
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                group:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                  - name
              required:
              - group
  "/admin/groups/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: show
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/group_response"
        '401':
          description: unauthorized
    put:
      summary: update
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/group_response"
        '422':
          description: unprocessible entitiy
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/group_errors"
                name: GroupCreateErrorResponse
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                group:
                  type: object
                  properties:
                    name:
                      type: string
              required:
              - group
  "/admin/groups/{id}/users/{user_id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    put:
      summary: add_user
      operationId: groupsAddUser
      responses:
        '200':
          description: successful
    delete:
      summary: remove_user
      operationId: groupsRemoveUser
      responses:
        '200':
          description: successful
  "/session":
    post:
      summary: login
      operationId: login
      parameters: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/session/logout":
    get:
      summary: delete session
      operationId: logout
      responses:
        '200':
          description: successful
  "/admin/users":
    get:
      summary: list
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                name: UsersListResponse
                type: array
                items:
                  "$ref": "#/components/schemas/user_response"
        '401':
          description: unauthorized
    post:
      summary: create
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_response"
        '422':
          description: unprocessible entitiy
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_errors"
                name: UserCreateErrorResponse
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    group_ids:
                      type: array
                      items:
                        type: integer
                  required:
                  - name
                  - username
                  - password
                  - password_confirmation
              required:
              - user
  "/admin/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: show
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_response"
        '401':
          description: unauthorized
    put:
      summary: update
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_response"
        '422':
          description: unprocessible entitiy
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_errors"
                name: UserCreateErrorResponse
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    group_ids:
                      type: array
                      items:
                        type: integer
              required:
              - user
  "/admin/users/{id}/groups/{group_id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: group_id
      in: path
      required: true
      schema:
        type: integer
    put:
      summary: add_group
      operationId: usersAddGroup
      responses:
        '200':
          description: successful
    delete:
      summary: remove_group
      operationId: usersRemoveGroup
      responses:
        '200':
          description: successful
components:
  schemas:
    attribute_error:
      type: array
      items:
        type: string
    group_response:
      name: GroupResponse
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    group_errors:
      type: object
      properties:
        name:
          "$ref": "#/components/schemas/attribute_error"
    user_response:
      name: UserResponse
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        group_ids:
          type: array
          items:
            type: integer
      required:
      - id
      - name
      - username
      - group_ids
    user_errors:
      type: object
      properties:
        name:
          "$ref": "#/components/schemas/attribute_error"
        username:
          "$ref": "#/components/schemas/attribute_error"
        password:
          "$ref": "#/components/schemas/attribute_error"
        password_confirmation:
          "$ref": "#/components/schemas/attribute_error"
        group_ids:
          "$ref": "#/components/schemas/attribute_error"
