// JsFromRoutes CacheKey 390350b45ba743e535a1519d1ecd440a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/admin'),
}
