// JsFromRoutes CacheKey a476db9f2d9ec45130688dd04f9ff4a5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/forward_auth'),
  login: /* #__PURE__ */ definePathHelper('get', '/forward_auth_login'),
}
