// JsFromRoutes CacheKey 3be240b5c6c1fe68ba4403da607bed05
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/groups'),
  create: /* #__PURE__ */ definePathHelper('post', '/groups'),
  new: /* #__PURE__ */ definePathHelper('get', '/groups/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/groups/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/groups/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/groups/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/groups/:id'),
}
